name: The Way I See It...
favicon: null
layout_spectrum: 0.9051988127175719
typography_spectrum: 0.7117800915148109
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5835282492917031
  lightness: 0.180627180961892
  saturation: 0.7082436501514167
  rhythmicContrast: 0.5572949408087879
purpose: []
